# Generated by Django 4.2.7 on 2023-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="posted",
            field=models.CharField(default="N/A", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
